### ISSUE TITLE
Migrate FixedGridLayoutManager.java to Kotlin

### ISSUE THREAD

**Issue by lucasnlm** [lucasnlm/antimine-android#101]
[FixedGridLayoutManager.java](https://github.com/lucasnlm/antimine-android/blob/master/common/src/main/java/dev/lucasnlm/antimine/common/level/widget/FixedGridLayoutManager.java) was reverted to Java and it would be nice translate it to Kotlin. Since it's a very large class It must be done carefully.

**Comment by WildOrangutan** [comment]
Do you mind if I do that? I'm not really a first timer, but I would need to hone my Kotlin skills 😊

**Comment by lucasnlm** [comment]
@WildOrangutan Of course!
Just pay attention on Android Studio automatic Java -> Kotlin translator. It works well but with this class it doesn't.
