### ISSUE TITLE
Previous games menu leads to a crash

### ISSUE THREAD

**Issue by Go-rom** [lucasnlm/antimine-android#106]
Hello,

First, thank you for this nice app !

i recently updated to 7.1.1 and encountered a bug.
When i try to reach the previous games, the app crashes. (Android 6.0.1)

Since 7.1.4 is now out but not available on F-Droid yet, you might have already fixed this one. 
In that case, this ticket can be closed.

**Comment by lucasnlm** [comment]
Thanks for report it!
7.1.4 fixes this issue.
It was a bug with Dugger Hilt.

**Comment by Go-rom** [comment]
Ok thank you !
