### ISSUE TITLE
Impossible board

### ISSUE THREAD

**Issue by rvandegrift** [lucasnlm/antimine-android#109]
Saw this board today.

![oops1](https://user-images.githubusercontent.com/976207/85906219-7f917900-b7c2-11ea-9aed-b30f547808bf.png)
![oops2](https://user-images.githubusercontent.com/976207/85906221-802a0f80-b7c2-11ea-89d2-ffc8a4bef7de.png)

**Comment by lucasnlm** [comment]
Hi!
Is it scrollable horizontally or it wasn't possible?
I did not understand yet. 😅

**Comment by rvandegrift** [comment]
Haha, I didn't realize I could scroll.  I saw the numbers of the right hand edge and thought they had to be incorrect.  Thanks!
