### ISSUE TITLE
Wrong remaning mines number

### ISSUE THREAD

**Issue by Go-rom** [lucasnlm/antimine-android#112]
Hello

When you resume a previous ongoing game, mines counter displays the total number of mines instead of the hidden remaining mines

Here's a screenshot : 
![Screenshot_2020-06-30-22-57-39](https://user-images.githubusercontent.com/1423386/86178347-7ee14580-bb28-11ea-8642-9eefdb52c081.png)

Spotted with 7.1.4 version

I checked the changelog related to 7.2.0 and 7.2.1 but didn't see any comment about this one

**Comment by lucasnlm** [comment]
You are right. I was very easy to reproduce.

**Comment by lucasnlm** [comment]
Thanks for report it!
I will be fixed by #113 
And will be on `7.2.2+`.
