### ISSUE TITLE
Open cell on first click when Click is set to quick flag

### ISSUE THREAD

**Issue by sergeiwork** [lucasnlm/antimine-android#115]
If we set control scheme to Double click then single click will place flags. But there is no need to place flag on first cell you trying to open. So on first click we should always open cell. Quick and stupid fix will be to add if in ActionResponse.SwitchMark.

common/src/main/java/dev/lucasnlm/antimine/core/control/GameControl.kt line 297
```
if (!hasMines) {
    plantMinesExcept(id, true)
    openTile()
    0 //not sure about that 
} else if (isCovered) switchMark()
    1
```

I'm not that good at kotlin to make a pull request. But change is literaly couple lines of code.

**Comment by lucasnlm** [comment]
Thanks for you feedback!
It makes sense!
Your code is right BTW.
I tested the following:

```kotlin
            ActionResponse.SwitchMark -> {
                if (!hasMines) {
                    plantMinesExcept(id, true)
                    openTile()
                } else if (isCovered) {
                    switchMark()
                    1
                } else 0
            }
```

Just adding the `else 0`. `openTile()` already returns the number of changed views, so that `0` is not needed there.

**Comment by lucasnlm** [comment]
I've open #116 with your code and some tests to it.

**Comment by sergeiwork** [comment]
Ok I see. I haven't figured that openTile will return number of tiles. Thank for quick reply!
