### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by lucasnlm** [lucasnlm/antimine-android#121]
## Localization

You can help translate or review the game via [crowdin](https://crowdin.com/project/antimine-android).

## Review

You can also help translate the texts from [fastlane folder](https://github.com/lucasnlm/antimine-android/tree/master/fastlane/metadata/android).

**Comment by geftimov** [comment]
Can we add additional languages?
I am thinking of Bulgarian

**Comment by lucasnlm** [comment]
@geftimov Of course! I've just added Bulgarian there. :smile: 
`https://crowdin.com/project/antimine-android/bg`

**Comment by lucasnlm** [comment]
@geftimov Your translation will be merged with #128
Thank you very much!

**Comment by adripo** [comment]
Can you add the "hacktoberfest" topic in your project's About please, so the pr is elegible to hacktoberfest?

**Comment by lucasnlm** [comment]
@adripo Added `hacktoberfest` topic.

**Comment by WildOrangutan** [comment]
Are there any limits, to which language you want to translate? Is any language welcome?

**Comment by lucasnlm** [comment]
@WildOrangutan You can add a new language if it's not already listed on strings.

**Comment by tux-ware** [comment]
Hello, I just joined the project via crowdin platform. I would like to add a Slovak translation. How do I do that? Shall I do a fork on github and then do the pull request, or can I add Slovak translation directly via crowdin?

**Comment by lucasnlm** [comment]
@tux-ware Hi! Thanks for your interest! :)
I just added Slovak on crowdin. So all you need to do is translate there.
When finished, it will export and update the translation here.

This is the link: https://crowdin.com/project/antimine-android

**Comment by mondlicht-und-sterne** [comment]
i am finished the german translation now
