### ISSUE TITLE
"Controls" setting ignored in custom sized games

### ISSUE THREAD

**Issue by slckl** [lucasnlm/antimine-android#125]
I'd just like to say, this is a very lovely game, done beautifully.

However, I prefer the double click to open tile, but this setting does not seem to work in "Custom" difficulty.

Here's how it repros for me:
1. start a normal game
2. set control to double click, works ok
3. start a custom game (say, 8x16, 30 mines)
4. check control, still at double click
5. but single click will open, instead of flag now...

In fact, changing control to "flag-first" will also do nothing, and game will keep playing with "Standard" controls.

**Comment by lucasnlm** [comment]
Thanks for your feedback! :smile: 

Indeed, this bug is really happening. :disappointed: 
I will fix it and send a update ASAP.

If you use F-droid it my take up to 7 days, PlayStore will took about 2 days.

**Comment by geftimov** [comment]
The same problem happens if you retry a game.
Then the controls saved are lost.

**Comment by lucasnlm** [comment]
@geftimov Thanks for report it. :smile: 
It was the same root cause. I hope `7.2.4` fix both of these bugs.

**Comment by slckl** [comment]
Newest version allows me to the double-click control scheme in custom-sized games as well, yay!

As far as I'm concerned, the issue can be closed.
