### ISSUE TITLE
[Feature request] Add stats reset

### ISSUE THREAD

**Issue by Go-rom** [lucasnlm/antimine-android#129]
Hello,

it would be great to be able to reset the stats.

Thanks !

**Comment by lucasnlm** [comment]
A specific stats or all of them?

**Comment by Go-rom** [comment]
I was thinking all of them.

9 juil. 2020 14:50:02 Lucas Nunes <notifications@github.com>:

**Comment by lucasnlm** [comment]
I will be added with #130

**Comment by Go-rom** [comment]
Nice, thank you !

10 juil. 2020 01:14:15 Lucas Nunes <notifications@github.com>:
