### ISSUE TITLE
Last F-Droid builds failed ?

### ISSUE THREAD

**Issue by Go-rom** [lucasnlm/antimine-android#132]
Hello,

I got some updated apps the last week with F-Droid but got nothing for Antimine (i was waiting for 7.2.4)

I'm not really aware about how F-Droid really works but i did some checks and here's what i got.

The last successful build is 702021 as you can see [here](https://f-droid.org/wiki/page/dev.lucanlm.antimine/lastbuild_702021)
But the following builds [702031](https://f-droid.org/wiki/page/dev.lucanlm.antimine/lastbuild_702031), [702041](https://f-droid.org/wiki/page/dev.lucanlm.antimine/lastbuild_702041) and [702061](https://f-droid.org/wiki/page/dev.lucanlm.antimine/lastbuild_702061) provide a smaller report with this line : "could not bring up vm 'builder_default'

Do you know what's happening with these builds ?

**Comment by lucasnlm** [comment]
I will check what happend with F-Droid.
Thanks.

**Comment by Go-rom** [comment]
The last build [702071](https://f-droid.org/wiki/page/dev.lucanlm.antimine/lastbuild_702071) has succeeded, thank you.

**Comment by lucasnlm** [comment]
Thanks for report!
