### ISSUE TITLE
More themes

### ISSUE THREAD

**Issue by diegomalone** [lucasnlm/antimine-android#140]
It would be nice to have colors on the numbers. It would also be nice to have the ability to change themes.

**Comment by lucasnlm** [comment]
Hi, Diego!
Thanks for your feedback!
Do you mean change only the number colors?

About theme, currently there are two: default and dark theme. Dark theme is used when your Android is on Dark mode (there's no way to force it currently). And I hope to add a new `Themes` screen soon.

**Comment by diegomalone** [comment]
My device is on dark mode and I hadn't seen the light theme yet. Playing without colors is confusing for me. However, I am happy to know that you are working on themes.

**Comment by lucasnlm** [comment]
Now It makes sense. 😄
On dark mode the numbers are using the same color.

Again, thanks for your feedback!

**Comment by lucasnlm** [comment]
Themes will be added by #144

**Comment by lucasnlm** [comment]
Added on `8.0.2+`
