### ISSUE TITLE
Can you please bring back the amoled black theme? 

### ISSUE THREAD

**Issue by Fatcakes** [lucasnlm/antimine-android#158]

**Comment by lucasnlm** [comment]
Hi!

@Fatcakes What version are you using?
I didn't remove the dark theme. On `8.0.0` I've added a `Themes` session.

BTW, the Dark Theme is not an AMOLED theme, what gives me the ideia of add a true AMOLED theme as well. 😄

**Comment by lucasnlm** [comment]
Added on `8.0.5`.
