### ISSUE TITLE
Getting unknown installation error on fdroid

### ISSUE THREAD

**Issue by nitrocode** [lucasnlm/antimine-android#174]
I'm using Google pixel 3, red moon disabled, and getting an unknown installation error from fdroid when installing antimine. This used to work and I can no longer install older builds either.

I downloaded the same app from the play store and it worked correctly. Is the one from the play store coming from the same author?

**Comment by lucasnlm** [comment]
They are both from the same author. However I don't think this `unknown installation error` is related to this app, but to F-droid client. Have you tried clean F-droid cache?

**Comment by nitrocode** [comment]
Unfortunately, same issue after clearing cache. I tried uninstalling and reinstalling fdroid as well. Other apps from fdroid can be installed except for this one.

**Comment by lucasnlm** [comment]
`unknown installation error` is not a good message :sweat_smile: 
I will check on F-droid forum if I get more info.

**Comment by nitrocode** [comment]
I should add that I'm running the latest Android 11.

**Comment by Porkepix** [comment]
For your information, just checked what was the last unsupported application for Android 11, so I guess https://gitlab.com/fdroid/fdroiddata/-/issues/2162 might be of interest to you :)

**Comment by nitrocode** [comment]
Interesting. I don't see this app on that list. Does antimine also target sdk 30?

**Comment by nitrocode** [comment]
@Porkepix looks like the maintainer in that thread fixed this app around a month ago.

I tried to install antimine from fdroid today and it worked. Thank you to that maintainer and to you for finding that thread.
