### ISSUE TITLE
Allow panning beyond edge

### ISSUE THREAD

**Issue by daniellandau** [lucasnlm/antimine-android#189]
It is not equally easy for me to reach all parts of the screen with my thumb. If you could move the game so that there's more gray edge after the grid ends, I could bring also the edges and corners to my good reachability zone.

**Comment by lucasnlm** [comment]
Hi!
Thanks for your feedback!

If you mean something like this:

<img src="https://user-images.githubusercontent.com/1326126/102423890-c8dfba00-3fe8-11eb-851b-6668f111456a.png" width="300px"/>

It will be added on `8.5.0` :smile:

**Comment by daniellandau** [comment]
Yes thank you this is what I meant!

I'd personally allow panning even slightly further away, but it's your app so you make the call.
