### ISSUE TITLE
Chording on single tap

### ISSUE THREAD

**Issue by daniellandau** [lucasnlm/antimine-android#190]
Currently (on f-droid version) double tap does chording as described in https://github.com/lucasnlm/antimine-android/issues/57. I'd like the option to do it on single tap to play the game as fast as possible on a touch screen.

**Comment by lucasnlm** [comment]
Hi! Thanks for your feedback!
I hope that 535269f46c79be05d3a8bf22838ba3d3b5e7ea4d does what you want :)
It should be available on `8.3.8`.

**Comment by daniellandau** [comment]
It does, thank you!
