### ISSUE TITLE
Control schemes only takes effect after restart the game

### ISSUE THREAD

**Issue by fagnerln** [lucasnlm/antimine-android#205]
I noticed that some control schemes don't work as desired, so I set it and close the app. When I resume the game, the control works well as it setted before.

--------------------------------------------
Como inglês não é minha língua nativa, tentarei entrar em mais detalhes em PT-BR mesmo. Eu sempre joguei com os controles padrão, mas percebi que muitos teem dificuldade com os controles, mesmo os alternativos. Fui testando todos, vi que realmente não estavam funcionando bem, até que retornei para o padrão e não conseguia mais colocar bandeiras (segurar). Fechei o aplicativo, reabri e notei que estava normal, daí fui testando os outros formatos e consegui utilizar da forma planejada.

**Comment by lucasnlm** [comment]
Olá!
Pode verificar se esse problema ainda ocorre com você?
Obrigado!

**Comment by fagnerln** [comment]
Claro!
Eu já não me lembrava sobre como era o bug, por sorte ainda estava com uma build antiga do jogo em que consegui reproduzir, atualizei ele e na nova versão o bug já não ocorre mais, troquei várias vezes e os controles atualizaram corretamente.
O novo menu está ótimo, parabéns.
