### ISSUE TITLE
Bugs with the black theme

### ISSUE THREAD

**Issue by fagnerln** [lucasnlm/antimine-android#206]
I tried all the themes, only find a bug with the black one. There's something specific with it.
When I scroll down, it breaks the text and images.

Another bug with themes:
My brother find another bug that I can't reproduce, I don't know if it's specific to PlayStore version (as I use the F-Droid), but for some reason, if he closes the app, it returns to the default theme

![WhatsApp Image 2020-10-31 at 13 37 30](https://user-images.githubusercontent.com/18636416/97785702-7146d580-1b85-11eb-9ea5-29ac1cf7abfd.jpeg)

**Comment by lucasnlm** [comment]
I couldn't reproduce this bug on my device. What App version and Android are you using? And your brother's app version?

**Comment by fagnerln** [comment]
I'm on a Moto e6s (XT2053-2), Android 9, Antimine 8.3.4 (Fdroid)

I don't know how you made the themes, but probably there's some specific to the black theme that doesn't fit on my resolution (maybe some texture?), which is 1424x720.

My brother have a Moto e5 play, Android 8.1, Antimine 8.3.4 (GPlay), but as he doesn't live here, I can't do more tests, and like I said, I can't reproduce the bug on my device.

**Comment by lucasnlm** [comment]
I will try using Android 9 emulator. About your brother issue, if he clicked on "Try It" button to set the theme it will be reseted after restart the game. But I'm will check if it's possible to happen on other context.

Thanks for report this bug!

**Comment by lucasnlm** [comment]
Aliás, agora que eu reparei que você fala português 🤦‍♂️.

**Comment by fagnerln** [comment]
É preferível o inglês para caso algum extrangeiro vem contribuir, facilita. Eu arranho um inglês, dependendo do texto levo muito tempo para redigir, como eu queria explicar melhor o outro bug e você é brasileiro, chutei o balde... Hehe

Tenta comparar um tema com o outro, é só o preto que dá essa falha (talvez alguma configuração no botão de seleção de tema?)

Quanto ao bug dele, nem eu e nem ele encontramos esse botão de "try it" ou sei lá o que é em português, o único botão na tela de tema é o da lixeira.

**Comment by lucasnlm** [comment]
I was able to reproduce this bug using Android 9. It affects only AMOLED theme.
It will be fixed by 4c12b3167c81b012009ec0982f275be180a9294c.

Thanks for reporting it! 👍

**Comment by fagnerln** [comment]
It's fixed on 8.3.8! Thanks!
