### ISSUE TITLE
Auto-flag is not really working

### ISSUE THREAD

**Issue by atomizer** [lucasnlm/antimine-android#221]
Since there is no description on the feature, what I was expecting is that open squares with a number that have exactly that many unopened neighbours would get flags placed around them. An example of a state that was reached without placing any flags manually, with the feature enabled:

![](https://user-images.githubusercontent.com/418303/103105178-0c67a300-463d-11eb-93f0-5359f29bf495.png)

Seems like it works randomly, but not very often. In the end it's not really helpful at all, in complex cases I still have to switch to flags and manually place them.

**Comment by lucasnlm** [comment]
Thanks  for reporting it!
I think it really doesn't work so well for complex cases. I will try to improve it.
