### ISSUE TITLE
Illogical playfield generated

### ISSUE THREAD

**Issue by lma-gh** [lucasnlm/antimine-android#224]
See this screenshot of a game (note the obviously contradicting numbers in the top left corner):

![https://i.postimg.cc/3RbqTR8V/Screenshot-20201229-181104-dev-lucanlm-antimine.jpg](https://i.postimg.cc/3RbqTR8V/Screenshot-20201229-181104-dev-lucanlm-antimine.jpg)
.
 

I /think/ I got there after hitting a bomb, pressing the retry button and then playing until I reached the state shown.

Level is "Intermediate".

After clicking on the remaining tiles (hit bomb first, then clicked on "Continue"), I get this:

![](https://i.postimg.cc/fRmkSt17/Screenshot-20201229-182005-dev-lucanlm-antimine.jpg)

**Comment by lma-gh** [comment]
OMG.

The playing field is horizontally **scrollable**!

This is ... not very intuitive, to say the least.

Well, at least this bug report can be either closed or turned into a wishlist bug report titled "Configure playfield scrollability and clearly indicate whether it is set to scrollable or not."

**Comment by lucasnlm** [comment]
Yeah. Indeed.  :sweat: 
The scroll is not so obvious :disappointed: .
I will add an way to indicate where the scroll is and indicate that there's a scroll in the game.

Thanks for your feedback! :+1:

**Comment by BinToss** [comment]
Perhaps a smaller checkerboard pattern would better indicate the level's bounds.
