### ISSUE TITLE
Trigger Long Press without lifting finger

### ISSUE THREAD

**Issue by wbrawner** [lucasnlm/antimine-android#230]
The standard behavior for long press on Android is to trigger it without lifting your finger. It seems that I have to lift my finger before the long press is registered in the game though, which is a bit confusing and took me a little while to figure out.

**Comment by lucasnlm** [comment]
Thanks for your feedback! 
Makes sense! I think this is happening due to an issue with double-click. I will investigate it deeply soon.

**Comment by wbrawner** [comment]
I'd be happy to help contribute a fix as well if you'd like

**Comment by lucasnlm** [comment]
@wbrawner Feel free to try fix it. :smile: 
I'm still working on some other fixes, so I can't work on it yet.
