### ISSUE TITLE
Menu headings are cut off when system font size is increased

### ISSUE THREAD

**Issue by nevillepark** [lucasnlm/antimine-android#247]
When I increase the system font size from "Default" to "Large"/"Largest" in Android's accessibility settings, the bottom part of the headings for each section of the menu is cut off. I am using Lineage OS 17.1, based on Android 10.

![Screenshot](https://user-images.githubusercontent.com/16054979/109428105-7e54c380-79c3-11eb-88ad-b8e1a8795c54.png)

**Comment by lucasnlm** [comment]
Thanks for reporting that!

**Comment by lucasnlm** [comment]
Fixed on 9.1.1
