### ISSUE TITLE
wrong display for "help points received"

### ISSUE THREAD

**Issue by guntbert** [lucasnlm/antimine-android#251]
Commit 2e43f957cdd7cbb4b716e6136fba793a9b020fe2 introduced a bug where with "help" enabled  the Game Over Display shows 
> You have received: 2

which isn't reflected in the actual number of help flags (you still get just +1).

It seems that the line https://github.com/lucasnlm/antimine-android/blob/2e43f957cdd7cbb4b716e6136fba793a9b020fe2/app/src/main/java/dev/lucasnlm/antimine/GameActivity.kt#L662 changes the displayed value but  there is no change in the calculation of the count for the help flags.

**Comment by lucasnlm** [comment]
Thanks for report it!

**Comment by lucasnlm** [comment]
Fixed on `10.0.0+`
