### ISSUE TITLE
Big delay between tapping a tile and the tile getting getting revealed

### ISSUE THREAD

**Issue by Duvio** [lucasnlm/antimine-android#254]
When i press a tile, there are like a few hundred milliseconds where the tile lights up (because i tapped it) and it getting revealed

This is annoying because it slows you down and destroys the ability to do speedruns

**Comment by lucasnlm** [comment]
Hi @Duvio !
Thanks for your feedback! 
This probably is more visible on big maps while the game tries to find a map that doesn't need guessing (this can be disabled on settings).

I'm currently working on a new rendering way, so the next update is expected to be faster.


I'll check if I can do something to improve this startup time.

**Comment by Duvio** [comment]
I wasnt talking about the time the map takes to generate when the game starts. I meant the time it takes for a tile to change from unrevealed to revealed after being tapped. I disabled the "no guessing" mode, but nothing changed

I attached a video to show you what i mean. In the video you can see that it takes a little amount of time for a tile to change its status after being tapped. It's difficult to see it in the video, but when playing it has a notable delay

https://user-images.githubusercontent.com/29256280/112490959-228e1800-8d80-11eb-9c40-df5012231845.mp4

**Comment by lucasnlm** [comment]
Hi!
@Duvio Can you check it works better on `10.0.4+`?

**Comment by Duvio** [comment]
I cant find an APK of the new version and the new update is not available on FDroid, otherwise i would test it immediately

**Comment by lucasnlm** [comment]
@Duvio Hi! It's available on F-droid now. Can you test it again?

**Comment by Duvio** [comment]
Yes, it works better and more smoothly now
Thanks
