### ISSUE TITLE
System them broken

### ISSUE THREAD

**Issue by linsui** [lucasnlm/antimine-android#263]
![IMG_20210408_233052](https://user-images.githubusercontent.com/36977733/114054690-9ac80380-987f-11eb-85fd-7f72f7c662e1.jpg)

**Comment by lucasnlm** [comment]
Hi!
Can you give more details?
Does it crashes as soon you open it?
Which version? Google or F-droid?

**Comment by linsui** [comment]
It's 10.0.3 from F-Droid. It works but the default theme is unreadable.
![IMG_20210409_081552](https://user-images.githubusercontent.com/36977733/114111158-cae7c480-98c8-11eb-9398-4000d50ccfe6.jpg)

**Comment by lucasnlm** [comment]
Ok! Thanks for report!
What it's your Android version and device?

**Comment by linsui** [comment]
Android 10, Xiaomi Mi 6

**Comment by lucasnlm** [comment]
Thanks!
It will be fixed by `10.0.4`
