### ISSUE TITLE
Time runs crazy

### ISSUE THREAD

**Issue by guntbert** [lucasnlm/antimine-android#267]
On 10.0.4+ the time runs with approximate double speed but somewhat "swing style" (as I would call it in music) 
I try to visualize a time line (the `+` denote the ticks)

    --+-+--+-+--+

I since found that this doesn't happen always. But it's not hardware dependant - occurs on the phone as well as in the simulator.

**Comment by lucasnlm** [comment]
Thanks for reporting it!
I will investigate.
