### ISSUE TITLE
Changing screen orientation resets the game

### ISSUE THREAD

**Issue by BloodRaven0** [lucasnlm/antimine-android#274]
Its like pressing continue from the menu loading some other previous game or starting a new one, and you cant switch the orientation back to continue.

This might be a symptom of the save/continue system not working correctly and not saving when it should.

Im on v10.0.4 from f-droid. I tried reinstalling, but the issue persisted.

**Comment by lucasnlm** [comment]
It looks like it happens only on the first game steps (right after open the minefield).
I will investigate more.

**Comment by BloodRaven0** [comment]
For me it happens at any point in the game, I was 3 squares away from beating a game when I tilted my hand just enough for the orientation to change, which reset my game, it's pretty annoying.

**Comment by lucasnlm** [comment]
Ok. 
I think I found the bug. I will be fixed on `10.1.4`

**Comment by BloodRaven0** [comment]
@lucasnlm Awesome!

By the way, I don't know if it has anything to do with this bug, but the "Standard" games are treated differently in portrait and landscape modes in the statistics tab. When in portrait, only standard games played in portrait will display as "Standard", the ones played in landscape will display as "Custom". Switching the orientation to landscape, the portrait games will show up as "Custom" and landscape ones become "Standard". Also, the games in landscape seem to be generated before the player clicks the first square (cuz it often only reveals one number, meaning there are mines next to the starting square), unlike the portrait ones that always have the starting square not surrounded by mines.

In hindsight, should I open separate issues for these, or will you do it?

**Comment by BloodRaven0** [comment]
I can confirm the rotation issues have been fixed in 10.1.5, although they are still counted as different game types in the statistics (as I explained on my previous comment). Also when you press new game, it instead continues the previous one if there is one in progress, instead of starting a new one (even if the previous is a different size).
