### ISSUE TITLE
No guessing

### ISSUE THREAD

**Issue by MrCavey** [lucasnlm/antimine-android#279]
Recently played a game on expert level with no guessing turned on and got to a 50/50 chance[Photo](https://ibb.co/Ct8G3nq)

**Comment by MrCavey** [comment]
Few more examples

https://ibb.co/phK2xSj

https://ibb.co/DzxNb4n

Both from same game

**Comment by lucasnlm** [comment]
Thanks for your feedback! :)
Yes. Currently the No guessing algorithm may fail in some circumstances (or it fails to find a 100% solvable map in a short period).
I'm currently thinking on a new version of it, so I will let your issue open until fix the algorithm.

**Comment by UniqueActive** [comment]
![Screenshot_20210522-052240_Antimine](https://user-images.githubusercontent.com/27487663/119213211-c7497f00-babd-11eb-9a2b-893e76067aef.png)

I also found a scenario like this. The corner is not solvable without a 50% guess between the cornerpiece and the one below. Perhaps more examples help with figuring it out, so I thought I should share :)

**Comment by yw662** [comment]
and this:
![Screenshot_20210615-015325](https://user-images.githubusercontent.com/34736747/122025617-5759ac00-cd7e-11eb-9c05-00cad6eee688.png)
a 50% guess on 3 mines.

**Comment by lucasnlm** [comment]
On the next update a warning will be shown when the level generator fail to create a guess-free minefield.
I hope this helps.

**Comment by BloodRaven0** [comment]
https://github.com/chrisboyle/sgtpuzzles
You can take a look at this puzzle compilation, it has minesweeper with a flawless no-guessing mode. I tried it with parameters that yours consistently fails with (standard mode with 40-50+ mines), and since it's open source, I thought you could take a peek at how they've done it.

**Comment by lucasnlm** [comment]
@BloodRaven0 I will take a look.

**Comment by lucasnlm** [comment]
@BloodRaven0 I was able to import the exact same algorithm from Simon Tatham's mines.
It will be added with #321 on version `14.2.0`.

An example of a minefield generated with this algorithm that wouldn't be generated by the old one:

<img src="https://user-images.githubusercontent.com/1326126/132960389-fe3acc83-2468-4eaa-92a9-f92be4cc0181.png" width="300px"/>

**Comment by BloodRaven0** [comment]
Awesome, I'm so excited about this!
