### ISSUE TITLE
Performance 

### ISSUE THREAD

**Issue by MrCavey** [lucasnlm/antimine-android#282]
On the new master level I'm experiencing a lot of slow down on my clicks. I'll do 2-4 quick clicks as I've done the calculations in my head and none of the register. I have to go back to click one and wait for it to register which seems to take over a second sometimes. This is frustrating when trying to get a really fast time.

If it helps in using a galaxy s20 ultra

**Comment by lucasnlm** [comment]
Yeah :(
It really have some performance issues with large maps.
It happens because of some recursive functions that run every time you tap.
It was worse before "Master" level. I had to make some optimizations before release the Master level.

Anyway, I'm still searching for optimizations points.

**Comment by lucasnlm** [comment]
@MrCavey Good news. It wasn't actually the main code. The code that controls the minesweeper takes less than 1ms even on Master level. I found another point related to the code that render the minefield taking more than 200ms on libgdx code. I'm working on this and It will probably be faster on the next release.

**Comment by lucasnlm** [comment]
@MrCavey I did some more optimizations. Now it can handle even huge maps (100x100 with 3k mines) with a good FPS. The only problem it that it takes some seconds to create the map.

**Comment by MrCavey** [comment]
Generating a large Firefox like that I would expect it to take a few seconds. That is livable, going for a fast time though is more important then waiting a second or two to let the board generate. Good job I look forward to testing it

**Comment by MrCavey** [comment]
Just tried master level and I have to say I didn't get frustrated because of lag once. I believe this issue can be closed.

**Comment by lucasnlm** [comment]
Thanks for test it again!
I hope 12.0.0 will be even faster
