### ISSUE TITLE
Master level

### ISSUE THREAD

**Issue by MrCavey** [lucasnlm/antimine-android#283]
This level seems easier than expert, way to many open spots and very little math or logic included, suggest upping mine count or shrinking size. 

Not really a bug per se but seems easy easier then expert level, some balancing needs to be done imo.

**Comment by lucasnlm** [comment]
Thanks for your feedback! :)
I will make some tests increasing the mine count.

**Comment by MrCavey** [comment]
300 is a good number, took me just about 7 minutes to finish that way.
