### ISSUE TITLE
[Feature Request/Improvement] Disallow open on flagged cells

### ISSUE THREAD

**Issue by njmdietrich** [lucasnlm/antimine-android#286]
think it would be great to make it impossible to open a flagged cell without unflagging it first. This would prevent a decent amount of "fat-fingering"

**Comment by lucasnlm** [comment]
Hi!
Thanks for your feedback / request. :)

I have some questions about your request (current game config). Which control style do you use? How did you open a flagged cell without unflag it first?
Currently using standard mode is not possible to open a flat without unflag it (or I'm missing something :sweat_smile: ).

**Comment by njmdietrich** [comment]
I am using the [Use button to switch between flag and open] control style. Being in the open mode is enough to be able to open flags.

**Comment by lucasnlm** [comment]
I just checked here and it seems to be a bug with this control style. It shouldn't open a flagged cell without remove it first.
I will fix it. :)
