### ISSUE TITLE
[question] Is "no guessing" effective in standard mode ?

### ISSUE THREAD

**Issue by yw662** [lucasnlm/antimine-android#287]
Standard is currently 9x18-36 for me, indeed much harder than expert. I actually have to guess in nearly every game.
Is the option not actively or is it just to hard ?

**Comment by lucasnlm** [comment]
Standard mode gets harder after every win you get. So, after some point, it may take too much time to find a "no guess" level and the algorithm fails. The more mines in a field, more difficulty is to find a "no guess" level.
I'm still trying to figure out a new algorithm, but currently it's not possible.

**Comment by AJS101** [comment]
Could you perhaps add a warning when the no-guess algorithm fails so the user doesn't waste time looking for a solution that doesn't exist?

**Comment by lucasnlm** [comment]
I will do that!
Good ideia!

**Comment by lucasnlm** [comment]
This feature has been added on `13.0.0`.
