### ISSUE TITLE
Issues in main menu with some specific themes

### ISSUE THREAD

**Issue by returnedinformation** [lucasnlm/antimine-android#290]
**Describe the bug**
The main menu is barely visible when using certain themes when the brightness is not at maximum. Screenshots available. 

**To Reproduce**
Select the theme and go to main menu

**Screenshots**
![Screenshot_20210620-111742_Antimine.jpg](https://user-images.githubusercontent.com/57621749/122668816-3f3cbf00-d1ba-11eb-85b7-21116e7d8e64.jpg)
![Screenshot_20210620-110736_Antimine.jpg](https://user-images.githubusercontent.com/57621749/122668825-46fc6380-d1ba-11eb-9cce-1ca93969f0a2.jpg)

**Android Version:**
Galaxy Note 8

**App Version**
12.0.0

**Comment by lucasnlm** [comment]
Fixed
