### ISSUE TITLE
"Tap on numbers" doesn't work when controls are set to use toggle button

### ISSUE THREAD

**Issue by Skirmisher** [lucasnlm/antimine-android#291]
When controls are set to "Use button to toggle between Flag and Open", the "Allow tap on numbers" setting has no effect. Tapping on a number with the correct amount of adjacent flags does nothing, in both Flag and Open mode.

**Android version:** 8.1
**App version:** 12.0.0

**Comment by lucasnlm** [comment]
It will be fixed on the next version.
