### ISSUE TITLE
Toggle button control incorrectly remembers state when resuming game

### ISSUE THREAD

**Issue by Skirmisher** [lucasnlm/antimine-android#292]
When using the "Use button to switch between Flag and Open" control scheme, resuming a game can result in the button showing the incorrect state. Specifically, if the button was in Flag mode and the player backs out to the menu, returning to the game with Continue shows the button with a flag icon, but in reality the game is in Open mode(!!). Tapping the button once changes the icon back to Open, but keeps the mode the same, so the button shows the correct icon from then on.

Note that this *only* happens if the player returns to the menu and then resumes the game without closing the app in between. If the app is restarted prior to continuing, the button shows the Open icon, and is correct.

**To reproduce**:
1. Change control scheme to "Use button to switch between Flag and Open"
2. Start or continue a game
3. Tap button to change to Flag mode, note that flags are placed correctly
4. Press Back to exit to menu
5. Press Continue to resume the game
6. Note button is still in Flag mode, but taps on the game field will open tiles instead of placing flags

**Android version:** 8.1
**App version:** 12.0.0

**Comment by lucasnlm** [comment]
Still happens on `12.1.0`.
I will fix it on `12.2`

**Comment by istudyatuni** [comment]
Hello @lucasnlm ! I have this bug on version 15.3.0

<details>

https://user-images.githubusercontent.com/43654815/147857975-a6505a27-c25c-47c3-8521-68ac9dbee9e8.mp4

</details>

**Comment by Skirmisher** [comment]
Hmm, I can indeed reproduce this on app version 15.3.0 (Android 9). In addition, resuming the game makes the timer tick up twice as fast! It appears as though there are two competing timer intervals set for incrementing the game timer.

**Comment by istudyatuni** [comment]
It works now, thank you!
