### ISSUE TITLE
Place "mode toggle" button in the top bar, instead of over the playing field

### ISSUE THREAD

**Issue by Skirmisher** [lucasnlm/antimine-android#293]
I don't use this mode myself, but my partner is frequently frustrated with the Material-style floating button in the toggle control scheme, because of how easy it is to accidentally tap the playing field if she doesn't tap the button dead-on. The placement near the bottom of the screen is convenient sometimes, but it would help in this case if the button were placed somewhere less likely to cause mistakes, like the top bar. Maybe an option for button placement would be best?

**Comment by lucasnlm** [comment]
Hi! @Skirmisher 
Is this what you mean?

<img src="https://user-images.githubusercontent.com/1326126/123975928-1d022880-d994-11eb-999b-f358e08fa77c.png" width="250px" />

**Comment by Skirmisher** [comment]
Yes, that's great :)

**Comment by lucasnlm** [comment]
Ok! It will be available on the next update! :)
