### ISSUE TITLE
Is this your app?

### ISSUE THREAD

**Issue by RickyM7** [lucasnlm/antimine-android#294]
This app is literally Antimine with other colors and is on Google Play with the same package name as your app:

https://play.google.com/store/apps/details?id=dev.lucanlm.antimine

I'm not sure if it's yours, so I decided to post it here!

**Comment by lucasnlm** [comment]
Yes. Since it's not open source and without any changes, it will check what I can do.

**Comment by lucasnlm** [comment]
I open a request on Google to remove that app. Since it's a complete copy (not even a fork with same changes) and it's not open source (requirement for GPL), It doesn't make sense allow it there.

**Comment by RickyM7** [comment]
Perfect! That's definitely the right thing to do.

**Comment by lucasnlm** [comment]
It was removed!
@RickyM7 Thank you very much!
