### ISSUE TITLE
Your apps don't have icons

### ISSUE THREAD

**Issue by RickyM7** [lucasnlm/antimine-android#295]
**Describe the bug**
I don't know if this is the best place to post this, but, I have the games "Antimine" and "Snake!" Installed on my phone and both do not show the icons correctly.
It's been a while since this happened, but I can't specify how long.

**Screenshots**
![Antimine-no-icon](https://user-images.githubusercontent.com/24703825/123934288-8587e000-d969-11eb-9240-7a839245b6a5.jpg)

**Android Version:**
7.0 (MIUI 11)

**App Version**
- Antimine: v12.1.1 (F-Droid)
- Snake!: v3.0.0 (GPlay)

**Comment by lucasnlm** [comment]
Thanks for report it! 
They should have icons. :sweat_smile: 

I will test using an emulator on Android 7.

Thanks!
