### ISSUE TITLE
Please update app/gradle/wrapper/gradle-wrapper.properties

### ISSUE THREAD

**Issue by linsui** [lucasnlm/antimine-android#298]
**Describe the bug**
app/gradle/wrapper/gradle-wrapper.properties is not updated to 6.5

**Comment by lucasnlm** [comment]
I just updated it to `12.4.2`.

https://github.com/lucasnlm/antimine-android/blob/master/app/gradle/wrapper/gradle-wrapper.properties

Is it failing to build on F-droid?

**Comment by linsui** [comment]
Yep. F-Droid detects gradle version from app/gradle/wrapper/gradle-wrapper.properties first so that 6.1.1 was used. Thanks!

**Comment by linsui** [comment]
Please update app/gradle/wrapper/gradle-wrapper.properties to 6.7.1. Thanks!

**Comment by lucasnlm** [comment]
@linsui I just updated all `/gradle-wrapper.properties` to ` 6.7.1` on `14.0.0`.
I hope it fixes the problem with F-droid build.

**Comment by linsui** [comment]
Thanks!
