### ISSUE TITLE
Single tap on number to clear surrounding mines

### ISSUE THREAD

**Issue by dylantjb** [lucasnlm/antimine-android#302]
**Is your feature request related to a problem? Please describe what the problem is.**
I primarily play by long pressing to flag, and short pressing a number to clear and I would love for this to be possible in the app.

**Describe the solution you'd like**
Implement an option to switch from long press to short press when tapping on numbers.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lucasnlm** [comment]
Hi! Thanks for your request.
What control style do you use?
I think click on numbers is possible in most of them.

**Comment by BloodRaven0** [comment]
What I did was set the "long press" delay really low, so my long presses are almost taps. The problem with this is that when you actually want to tap to reveal a square, it might take several tries.

**Comment by Alzarath** [comment]
It feels uncomfortable to use long-press to reveal surrounding blocks. Doing the same motion over and over (long-tapping to flag *and* reveal) does not feel like you're interacting with the game very consciously.

I would prefer to long-press exclusively to flag and tap to reveal tiles surrounding a revealed tile. Giving players the option is always nice. Might even be nice to be allowed to disable chording altogether.
