### ISSUE TITLE
wrong numbers in cells

### ISSUE THREAD

**Issue by neeels** [lucasnlm/antimine-android#303]
attached screenshot shows impossible numbers in indicator cells: the two "2" in top right corner are wrong.

![Screenshot_20210724-015037](https://user-images.githubusercontent.com/3238680/126851120-92ef101d-3366-49e0-867a-78f5a77dd798.png)

**Comment by lucasnlm** [comment]
Which "2" exactly?
Since there are covered areas there, it may be right.

**Comment by neeels** [comment]
isn't it obvious??

Here, I marked a couple of numbers that are definitely wrong,
(one of the four marked could be correct if the "2" below it were a "3" instead.)


![marked](https://user-images.githubusercontent.com/3238680/126915172-260b45b5-b416-4ac4-aba4-64371515d613.png)

**Comment by lucasnlm** [comment]
I thought it was with a specific "2".

But, considering the area out of the screen, it looks right for me.

![image](https://user-images.githubusercontent.com/1326126/127000977-e5743b2b-3bec-41f8-8bd6-4928e3abaea9.png)

**Comment by neeels** [comment]
I assume the area I see is the entire game board. The screenshot shows the entire screen of the phone. Are you saying that I can pan the board "under" the physical screen? If that is the case then close this issue as invalid.

argh just checked, and i just didn't realize that the board can be panned. Sorry for the noise...
