### ISSUE TITLE
Disparity in mine density between difficulties

### ISSUE THREAD

**Issue by BloodRaven0** [lucasnlm/antimine-android#306]
Here are the current mine densities, calculated per difficulty.
Standard (9x17, 47) - 30.72% (varies per games played)
Beginner (9x9, 10) - 12.35%
Intermediate (16x16, 40) - 15.63%
Expert (24x24, 99) - 17.19%
Master (50x50, 300) - 12%
Legend (100x100, 2000) - 20%

As you can see, besides standard, which is punishingly hard (and often impossible without hints), the difficulties have a linear progression of density, with the exception of Master, which is laughably easy, even easier than beginner in terms of density. It should have somewhere between 18%-19% density, which would give it 450-475 mines, a whole 50% more than it currently has.

Also, standard is challenging and all with its 30% (I read somewhere that it increases the more you play, which explains why it has gotten to this point for me), but at this point it can feel unfair, my first move often opening a square of 2-3 tiles with no move possible. Maybe introducing a cap to this difficulty increase (maybe 25% density?), or having the play field increase with it would work better.

**Comment by lucasnlm** [comment]
Agree about your points. I think I can increase the Master difficulty.

About the Standard, what do you think about increase the area to keep it in max of 25% density.

**Comment by BloodRaven0** [comment]
@lucasnlm 25% sounds good. You might need an algorithm about when to increase the width and when the length (one should be increased more often than the other to keep the aspect ratio, and don't forget to take landscape mode into account, which complicates things a little.
