### ISSUE TITLE
Cant win legend.

### ISSUE THREAD

**Issue by DoyleChris** [lucasnlm/antimine-android#325]
I have completed a Legend puzzle but dosent register it.
![Screenshot_20210923-105921_Antimine](https://user-images.githubusercontent.com/14863729/134532326-cb796aa3-ceec-449b-a374-45628df0f31a.jpg)

**Comment by lucasnlm** [comment]
Hi!
Thanks for your feedback.

Usually, when this happen is because there's a square flagged but without a mine in it.
Currently, there's no feedback in the game about it (I think I should add).

**Comment by lucasnlm** [comment]
Did the clock stop or is it running?

**Comment by DoyleChris** [comment]
running

**Comment by DoyleChris** [comment]
if all squares are covered and no flags left it should stop.  im having a hard time recreating.

**Comment by yw662** [comment]
It looks like there are still squares uncovered.

**Comment by PeterBindels-TomTom** [comment]
Have completed it twice now; it definitely works. The solvability guarantee also helps trust that it's doable. Haven't had any of the silly cornercases yet (where it puts a lot of mines in a corner). Can be closed IMO.
