### ISSUE TITLE
Wrong y position calculation and crash in landscape mode

### ISSUE THREAD

**Issue by Farbklex** [lucasnlm/antimine-android#339]
**Describe the bug**
The game seems to calculate the wrong y coordinate for the first clicked field. This also leads to a crash when the game is started and played in landscape orientation.

**To Reproduce**
Tested with Emulator:
- API 30
- Screen dimensions: 1440 x 2880

1. Click "New Game"
2. Select "Fixed Size"
3. Attach a debugger to `MinefieldCreatorNativeImpl.create(safeIndex: Int)` method
4. Click on the first field in the second row from the bottom left
5. Check what `y` coordinate was calculated in the method mentioned above. It is `0`.

Expected: 
`y` coordinate is `1`

**What control style do you use?**
Single Tap: Open, Long Tap: Flag

**Expected behavior**
Clicking the a first field in a game will reveal the correct field.

**Screenshots**
![Rounding error 2](https://user-images.githubusercontent.com/2601296/137995447-93dad584-e97e-467f-b862-e791d55a90c7.PNG)

**Android Version:**
30

**App Version**
versionCode 1500011
versionName '15.0.1'

**Comment by lucasnlm** [comment]
@Farbklex Thanks for report it! Great description BTW. :clap:
