### ISSUE TITLE
no guessing mode got broken

### ISSUE THREAD

**Issue by soundsbeard** [lucasnlm/antimine-android#342]
**Describe the bug**
i've installed this game first time about a month ago from fdroid.
i've played 100+ games in 'no guessing' mode and they were fine, no guessing indeed, unless the notification warned me its not.

i can't say exactly when it happened but i think that after the last update no guessing mode got broken.
i've played about 6 games after the update and each ended with guessing.
this is the last game:
 
![2021-10-23_15-34](https://user-images.githubusercontent.com/16347074/138556731-60fcaa8f-5f98-4e87-bb5a-6b7a0233fcef.png)

am i missing a safe move or it is really a dead end?
i've tried to turn it off and on again in the settings, but no luck.
is it possible to downgrade the app somehow to make sure im not crazy?

**To Reproduce**
start any game at intermediate difficulty on the version 14.3.0

**App Version**
14.3.0

**Comment by eladhen** [comment]
This isn't an unsolvable state (yet! I don't know what comes next).

Green are blocks that can be opened. Red are mines
![image17](https://user-images.githubusercontent.com/12398651/139638727-d6809665-8e4a-431d-83fb-9cac4b408d4a.png)
.

**Comment by soundsbeard** [comment]
> This state doesn't require guessing (yet! I don't know what comes next).
you are right, i wasn't thinking.

**Comment by lucasnlm** [comment]
@soundsbeard May I close this thread?
