### ISSUE TITLE
Performance drop when selecting solved numbers

### ISSUE THREAD

**Issue by melinate** [lucasnlm/antimine-android#347]
**Describe the bug**
Version 15.0.2 was fairly responsive when you selected a solved number to either expose cells with no bombs or mark the remaining cells as bombs. Since upgrading to 15.1.0 it can take >1 second to display the expected change.

**To Reproduce**
Select a 1 that is next to only one unsolved cell.

**What control style do you use?**
Single Tap Flag, Double Tap Open

**Expected behavior**
Bomb is immediately marked so the next number can be selected quickly.

**Screenshots**
NA

**Android Version:**
12 / Pixel 6 Pro

**App Version**
15.1.0

**Comment by lucasnlm** [comment]
You mean with "Highlight unsolved numbers" option enabled?
There's no significant change between 15.0.2 and 15.1.0, but the Highlight unsolved numbers" option. I will double check.

**Comment by theblackmallard** [comment]
> You mean with "Highlight unsolved numbers" option enabled? There's no significant change between 15.0.2 and 15.1.0, but the Highlight unsolved numbers" option. I will double check.

I was coming here to post this same bug. 
App Version 15.1.0
Android 10
installed from F-droid.

I don't have "Highlight unsolved numbers" option enabled and still have this delay. Basically when you click a revealed number it should either reveal bordering numbers or flag the remaining cells as bombs. This process has ~1 second delay from tapping the number to the flag being placed or other cells being revealed, when previously this was nearly instant. This delay appears to be blocking other interactions too. If you tap multiple cells before antimine flags/reveals the first one, the other cells won't reveal/flag, or sometimes reveal/flag out of order.

Manually flagging individual cells doesn't appear to have this delay, only when tapping revealed numbers to auto flag/reveal is there the delay.

**Comment by melinate** [comment]
I did not enable the new feature "highlight unsolved numbers" either. Just upgraded when 15.1.0 was released on F-Droid.

Thanks for looking into it.

**Comment by lucasnlm** [comment]
I will investigate what's happening. I seems to be happening only with the "Single Tap Flag, Double Tap Open" control style.

**Comment by lucasnlm** [comment]
I think I found the bug. I will release a new version with its fix asap.

**Comment by melinate** [comment]
Thanks for getting this fixed. I just tested the updated version and it
appears to be working as expected.

I have been using "tap open, long tap flag" while waiting for the new
release. While testing the latest version with "tap open, double tap tab
flag" it still feels a bit slower compared to "tap open, long tap flag"
for populating flags when single tapping a solved number, but it is so much
better now, and completely usable.

Thanks,
Nathan
