### ISSUE TITLE
toggle button resets for new game

### ISSUE THREAD

**Issue by bircher** [lucasnlm/antimine-android#354]
**Describe the bug**
When the flag is seleced in the switcher between opening and flagging it behaves as expected on the first game (which starts with opening, so you have to switch to flagging).
However when starting a new game (after winning for example) the switcher still shows the flag but it behaves like opening even after the initial uncovering. So if you for example click on a tip to flag it, it will open the mine and you loose. Even though the switcher tells you you are in flagging mode.

**To Reproduce**
win a game with the toggle set to the flag, start a new game from the win screen and then use a tip and try to set a flag there.

The workaround is to flip the switcher a few times.

**What control style do you use?**
You can check which control is selected on "Controls" screen.

![Screenshot_20220101-211014](https://user-images.githubusercontent.com/2198600/147859528-b8a6403e-36a9-4be3-8a2f-709b0eea81d5.jpg)

**Expected behavior**
Either start setting flags after the first uncovering when the switcher is set to flagging. (preferably)
Or the very least reset the switcher to opening so that one can tell that switching to flagging mode is needed.

**Screenshots**

![Screenshot_20220101-213716](https://user-images.githubusercontent.com/2198600/147859750-68601677-4733-4aac-a3fb-4698a40d2103.jpg)

**Android Version:**
11
**App Version**
15.3.0

**Comment by lucasnlm** [comment]
Thanks for report this bug. It will be fixed on `15.4.0`
