### ISSUE TITLE
Timer restarts too soon

### ISSUE THREAD

**Issue by melinate** [lucasnlm/antimine-android#355]
When continuing a game that was previously started. The timer starts before the game board is rendered. 

This is most noticable on Legendary game boards where the render time is longer. And impacts those games the most since the user is more likely to pause the game and continue later multiple times.

**Comment by lucasnlm** [comment]
It really happens. Since it takes a lot to load sometimes this is a problem. I will check if I can improve it.

**Comment by lucasnlm** [comment]
Thanks for report this bug. It will be fixed on 15.4.0 (I hope).
