### ISSUE TITLE
Flag Toggle Switch is turned off on Screen Rotation or Menu

### ISSUE THREAD

**Issue by zellchristensen** [lucasnlm/antimine-android#359]
**Describe the bug**
The flag toggle switch is turned off whenever the screen auto rotates or if you click back to visit the menu and then continue.

**To Reproduce**
Under controls, choose the option for "Use button to switch between Flag and Open"  and "Show Toggle Button on top bar"
Start a new game.
Set toggle button to Flag mode
Rotate device to cause auto rotate OR click the top left arrow to go to the menu then go back to continue.
Flag toggle is set to selection automatically.

**What control style do you use?**
"Use button to switch between Flag and Open"  and "Show Toggle Button on top bar"

**Expected behavior**
Last selected option is preserved.
While I've gotten used to checking it now, i had a few times where i intended to have flag mode on, unchecked an existing flag, then tried to set it again only to have it be on open mode and select a mine :)

**Android Version:**
11

**App Version**
15.4.0 (F-Droid build)

**Comment by lucasnlm** [comment]
It should be fixed on 1.6.0
