### ISSUE TITLE
Allow for greater number of Hints.

### ISSUE THREAD

**Issue by zellchristensen** [lucasnlm/antimine-android#360]
**Is your feature request related to a problem? Please describe.**
The hint limit of 25 seems too low.  

**Describe the solution you'd like**
Increase the amount of hints, maybe up to 100?

**Describe alternatives you've considered**
Maybe make the cap customizable in the settings or change dynamically based on the game type.

**Additional context**
When playing a Master game, I can easily score 40 hints after completion, but the limit is capped to 25 so I can't use the extra 15 at all.  When playing Legend mode, I often find myself needing way more than 25 hints and usually use all 25 while still having a couple hundred mines left.  Another factor is the randomness of the hints, like mentioned in https://github.com/lucasnlm/antimine-android/issues/305, as often I seem to waste multiple hints in the middle of an empty space, far from where I want them.

**Comment by lucasnlm** [comment]
I will think about it. It makes sense to support more than 25 hints in some cases 🤔 .

**Comment by lucasnlm** [comment]
As a quick-fix I will increase the hint limit to 100.
