### ISSUE TITLE
game failed on continue

### ISSUE THREAD

**Issue by valzu1** [lucasnlm/antimine-android#362]
**Describe the bug**
(At least legend) games failing when continuing. 

**To Reproduce**
Start legend difficulty game, play it for little bit at least, then close the app from game, not quitting via menu or anything. 
Later when going back to the app and selecting "continue" the timer doesn't continue running anymore, and by browsing the field it's possible to find a mine that is red. 
For some reason not all are red, and it has never given me the fail popup. 
I do have all of the assists on, I don't know if that somehow messes the game up...

**What control style do you use?**
You can check which control is selected on "Controls" screen.
Single tap flag, long tap to open

**Expected behavior**
The game should continue and not suddenly be lost when continuing. 

**Android Version:**
11
**App Version**
15.6.0

**Comment by lucasnlm** [comment]
Hi! 
Thanks for report this issue.
I reproduced it with any difficulty level by doing this:

Start a game, tap on a mine, tap on continue, return to menu, return to game.

There's something wrong with continue indeed. :(
I will take a look on this and update asap.

**Comment by lucasnlm** [comment]
Can you check if it still happens with `15.7.0+`?

**Comment by lucasnlm** [comment]
Can you check if it still happens with `15.7.0+`?

**Comment by valzu1** [comment]
Sorry but I’ve changed to iOS, I might check it one day but I’ve kind of put my Android phone out of use.

**Comment by westnordost** [comment]
I cannot reproduce this with 15.7.1
