### ISSUE TITLE
Progressive mode does not increase number of mines

### ISSUE THREAD

**Issue by juanmbt** [lucasnlm/antimine-android#364]
**Describe the bug**
When playing in Progressive mode the number of mines stops increasing after 76.

**To Reproduce**
1. Start a game in progressive mode and successfully complete a few games.
2. Start a new game and notice that the number of mines increases by 1.
3. Complete a few games until the number of mines is 76. Notice how a new game does not increase the number of mines anymore.

**What control style do you use?**
One touch: Open. Long touch: Flag

**Expected behavior**

**Screenshots**

**Android Version:**
11.0

**App Version**
15.6.0

**Comment by lucasnlm** [comment]
I hope it will be fixed by `15.7.1`.
