### ISSUE TITLE
Play Store Data Safety Section

### ISSUE THREAD

**Issue by vaibhavantil1** [lucasnlm/antimine-android#366]
Hi Team

In the recent Play Store policy, it will become mandatory for you to fill out the Data Safety Section. Since this is an OSS Android app, it will make sense to have it as a part of the repository as well.

I have run the scan using [my tool here](https://github.com/Privado-Inc/privado) on your repo, attached are
the scan results. I found the following 2 data types & 3 SDKs.

If this is helpful, do use our free tool to generate Play Store Data Safety report: https://github.com/Privado-Inc/privado

Also, do share your feedback & thanks for the OSS app 😄
![image](https://user-images.githubusercontent.com/87804852/156767994-90921bea-1dae-4594-b6bd-2fcac7fff9c5.png)
![image](https://user-images.githubusercontent.com/87804852/156768038-4699ca5d-982f-426b-a085-ead8a2e38886.png)
![image](https://user-images.githubusercontent.com/87804852/156768061-175e510f-25c9-4e54-953d-92e82e435cfe.png)

**Comment by lucasnlm** [comment]
Hi!
Do you have an example of how this can became part of the this repository?
It may be helpful.

**Comment by vaibhavantil1** [comment]
@lucasnlm - Best format is the CSV that users can import in Play Console directly. I have attached the sample CSV by Google, we generate ready to import CSV for you from our tool as well

[psl_csv_export_example - psl_csv_export_example (2).csv](https://github.com/lucasnlm/antimine-android/files/8211390/psl_csv_export_example.-.psl_csv_export_example.2.csv)
.
