### ISSUE TITLE
AppShortcuts

### ISSUE THREAD

**Issue by xmha97** [lucasnlm/antimine-android#387]
Please add some AppShortcuts for the new game.

![Screenshot_2022-10-21-22-11-54-717_com.miui.home.jpg](https://user-images.githubusercontent.com/23485114/197267606-dc2e519d-12d9-4780-9c71-bb4f6d56846c.jpg)

![Screenshot_2022-10-21-22-15-13-655_dev.lucanlm.antimine.jpg](https://user-images.githubusercontent.com/23485114/197268083-cc618f6b-aeec-4c8b-8d4c-d0b5e8910eac.jpg)

**Comment by lucasnlm** [comment]
Hi!
It was implemented once but had really low usage.
I can implement it again. :)

**Comment by lucasnlm** [comment]
<img src="https://user-images.githubusercontent.com/1326126/211965971-f99807fb-13b3-4e02-8c52-da3651d0f481.png" width="300px">

It will be available on the next update.
Thanks for the request. :)
