### ISSUE TITLE
add classic color theme

### ISSUE THREAD

**Issue by snooppr** [lucasnlm/antimine-android#388]
I tried all the themes, but not one of them does not have a normal display of squares.  This is a perversion for the eyes to peer.  Add a theme that shows squares without straining the eyes (classic).
![nines](https://user-images.githubusercontent.com/61022210/197939821-091057c8-5296-43f7-bd75-2e6f6f776e40.jpg)

**Comment by lucasnlm** [comment]
Hi!
I'm working on it. :)

![image](https://user-images.githubusercontent.com/1326126/201435526-995a78eb-6cb7-4de4-b3e7-339f58213292.png)
