### ISSUE TITLE
Add more sounds

### ISSUE THREAD

**Issue by xmha97** [lucasnlm/antimine-android#390]
Here is Windows 7 Minesweeper sounds.
Please add them to this project.
[Windows 7 - Minesweeper.zip](https://github.com/lucasnlm/antimine-android/files/9867203/Windows.7.-.Minesweeper.zip)
Thanks.

**Comment by lucasnlm** [comment]
I'm no sure if I can use these sounds. :(
They are not free and probably protected by Microsoft Minesweeper license.
But I agree with you that the game deserves more sounds.

**Comment by mr-islam** [comment]
Just discovered this app and got premium. Would love more sounds!

I really enjoyed the sounds from the Minesweeper bundled with the Google Play Games app, it has sounds for:

- Flag placed
- Successful ground clear
- Digging a bomb

Specially the first two kind of get me in the zone and flow state.

I'll try look for some royal free sounds that can be bundled... I'm sure there are some options online

**Comment by lucasnlm** [comment]
@xmha97 and @mr-islam I contracted a composer. Sounds and music should be available next month.

**Comment by mr-islam** [comment]
@lucasnlm Amazing, that's so awesome I can't wait 🌹🌹

**Comment by xmha97** [comment]
> @xmha97 and @mr-islam I contracted a composer. Sounds and music should be available next month.

Wow, thank you 👏

**Comment by xmha97** [comment]
> @xmha97 and @mr-islam I contracted a composer. Sounds and music should be available next month.

Wow, thank you 👏

**Comment by mr-islam** [comment]
This is awesome, thank you @lucasnlm! I'm in the Google Play beta and I didn't get the update yet, looking forward to it's release :)

**Comment by lucasnlm** [comment]
@mr-islam I decided to delay the Google Play release to fix all sound related bugs already reported. I will probably submit the new version today.
