### ISSUE TITLE
Master is mathematically easier that Expert

### ISSUE THREAD

**Issue by pcrazee** [lucasnlm/antimine-android#393]
**Describe the bug**
By calculating the "fields per mine" (number of fields divided by number of mines) for each difficulty, we can see that there are fewer mines per field in the master difficulty compared the the expert difficulty. In this regard I want to add, that even in legend mode, the presets in this game are easier than most other mines games.

**To Reproduce**
Calculate the fields/mine ratio for each difficulty preset.

**Expected behavior**
The fields/mine ratio becoming lower with higher difficulties.

**Android Version:**
12

**App Version**
16.1.1 (F-Droid)

**Comment by lucasnlm** [comment]
Fixed.

The ratios now have a test to ensure this won't happen again:

```
    Difficulty.Beginner to 12%,
    Difficulty.Intermediate to 16%,
    Difficulty.Expert to 17%,
    Difficulty.Master to 18%,
    Difficulty.Legend to 20%,
```
