### ISSUE TITLE
Can only donate with PayPal (forces you to make account)

### ISSUE THREAD

**Issue by JJRcop** [lucasnlm/antimine-android#395]
I have an account with PayPal but after they pulled the stunt of threatening fines for "bad speech" by users, I removed my payment details and I'm not adding them back.

I tried donating as a guest but PayPal no longer lets me do that; it pretends to but forces you to make an account or log in anyway.

Can you offer an alternative means of donating that allows for guest contributions without an account? I can no longer allow PayPal access to my payment info as a protest for what they did, and I want to donate for this lovely game.

**Comment by lucasnlm** [comment]
Hi!

Thanks for your support!
Is there any PayPal alternative that you'd rather use?
I actually don't know many.

**Comment by JJRcop** [comment]
Hey! This doesn't allow guest donating, but i'm ok with that: Github Sponsorship. You can actually accept donations from within GitHub directly. https://github.com/sponsors/

Even though I said 
> allows for guest contributions without an account?
I may have spoke too soon. There are platforms I'm fine with making an account for, and I already have one on GitHub. It might take a little bit to get approved though, there is a process.

Another alternative I see people using is https://ko-fi.com/


By the way, keep using PayPal if you feel comfortable with it, no worries! I just had a problem with using it now personally, but having multiple methods of donating doesn't hurt!

**Comment by lucasnlm** [comment]
I just enabled the GitHub Sponsors. 

I will add ko-fi later.
Thanks for the advice. :)
