### ISSUE TITLE
Secure backup denied

### ISSUE THREAD

**Issue by jcz1** [lucasnlm/antimine-android#396]
Hello.

I use SeedVault for secure (encrypted) backup apps and data to my device (USB) or my server (NextCloud).

But Antimine is opted-out from backups so it is not possible to save data by SeedVault :( Please can you allow encrypted backups? There is more info:

https://github.com/seedvault-app/seedvault/wiki/FAQ

And an example of commit:

https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71

Thanks.

**Comment by jcz1** [comment]
P.S. Seedvault is integrated in LineageOS, GrapheneOS etc.

**Comment by lucasnlm** [comment]
Hi!
Thanks for your feedback!
I'm currently working on `v17.0` update, so I will add this change in that new version.
Thanks again.

**Comment by lucasnlm** [comment]
@jcz1 Can you test it with the lastest version please?

**Comment by jcz1** [comment]
> @jcz1 Can you test it with the lastest version please?

Yes, it's fine now. Thanks a much! :-)
