### ISSUE TITLE
Flag icon is the same color as background

### ISSUE THREAD

**Issue by yephny** [lucasnlm/antimine-android#397]
**Describe the bug**
With the controls that use a toggle, the flag icon is the same color as the button's background. The reveal icon is visible, however. As far as I can tell, this is true only for the black-gray theme (2nd row on the left).

**To Reproduce**

1. Select the black-gray theme.
2. Switch controls to toggle.
3. Start or continue a game.
4. Check out and press the toggle button in the bottom right.

**What control style do you use?**
Toggle.

**Expected behavior**
The flag icon should also be black or gray like the reveal icon.

**Screenshots**
I can add a screenshot later.

**Android Version:**
LineageOS, Android 10.

**App Version**
16.1.1

**Comment by lucasnlm** [comment]
Thanks for reporting this bug.
It will probably be fixed on 17.0.0, since it will change the themes implementation completely and update Material Design 3.
