### ISSUE TITLE
Instant Win

### ISSUE THREAD

**Issue by ajchellew** [lucasnlm/antimine-android#4]
Start a new game, long press any square and you are greeted with "You won!" "All mines were disabled."

**Comment by lucasnlm** [comment]
I introduced this bug on latest version. :scream:
I changed the moment when victory is checked.
This happens because flag all mines is no longer a requirement to victory.

**Comment by lucasnlm** [comment]
Fixed by https://github.com/lucasnlm/antimine-android/commit/99f168da8e786cc42b0a1df2ac984cacbd22232e

Thanks to report!

**Comment by lucasnlm** [comment]
Fixed by https://github.com/lucasnlm/antimine-android/commit/99f168da8e786cc42b0a1df2ac984cacbd22232e

Thanks to report!
