### ISSUE TITLE
Regression: can't zoom in as far after updating to 17.1.1

### ISSUE THREAD

**Issue by the456gamer** [lucasnlm/antimine-android#406]
**Describe the bug**
Today my game prompted (and I updated to) 17.1.1 on the play store, which includes updates to the settings menu
Which has removed customisability functionality.
This include changing the size of tiles, which allows for more controllable zoom, which I consider a feature to make touch targets bigger, and reduce cognitive load.

Sidenote, the new theme bar is not clear that you can swipe to choose more styles

**To Reproduce**
Open themes settings, see that the size slider is not present

**What control style do you use?**
Single flag, long open

**Expected behavior**
Ability to change size , and make it the same size / bigger

**Max zoom Screenshots**
V17.1.1 (playstore)
![v17.1.1 (playstore)](https://user-images.githubusercontent.com/42748092/217478515-b6d022b0-ae00-4047-910b-f5fe7945ca0a.png)
V16.1.1 (fdroid)
![v16.1.1 (fdroid)](https://user-images.githubusercontent.com/42748092/217478549-841cb5c6-d634-41cd-a6e0-a791abd6eb06.png)

**Android Version:**
16.1.1

**App Version**
16.1.1 -> 17.1.1

I'm not sure what playstore version I updated from
But I cant remember the previous

**Comment by lucasnlm** [comment]
Thanks for your feedback.

If it be able to zoom in more that currently is, it will solve your problem?

I removed the customization options because I believe the "skins" can do the same in a simpler way. And I agree with you about the discoverability (I will change that).

**Comment by the456gamer** [comment]
Yeah I think that would work

**Comment by lucasnlm** [comment]
@the456gamer can you confirm if this is still an issue on current version, please?

**Comment by the456gamer** [comment]
No, Thank you for your help!
