### ISSUE TITLE
System Theme

### ISSUE THREAD

**Issue by xmha97** [lucasnlm/antimine-android#408]
Please support the system default theme by default.
After installing, I see this app is light but my phone is dark.

**Comment by lucasnlm** [comment]
@xmha97 What version of Android are you using? What phone?
Can you give more details?

**Comment by xmha97** [comment]
I am using the latest version on F-Droid.
My phone is Xiaomi T11 (Android 12)

**Comment by lucasnlm** [comment]
@xmha97 I still couldn't reproduce this issue. Maybe it's something too specific. But I will keep this thread open if we find more information.

**Comment by lucasnlm** [comment]
Can you check if [17.1.7 apk](https://github.com/lucasnlm/antimine-android/releases/tag/17.1.7) works for you?

**Comment by xmha97** [comment]
Hi, the "System Default" theme working but it not active by default.

https://user-images.githubusercontent.com/23485114/222376666-8a8136ff-e274-4b6c-a0ff-4d255cfa72f0.mp4

**Comment by lucasnlm** [comment]
That's correct. Light theme is the default. After Material You support, the system theme may use ugly color combinations and users think it's app fault. But I can revert this change on F-droid build.

**Comment by lucasnlm** [comment]
I will close this thread. :+1: 
System theme will be default on F-droid on 17.2.3+.
