### ISSUE TITLE
Custom mode: lack of input sanitization

### ISSUE THREAD

**Issue by Defiect** [lucasnlm/antimine-android#418]
The params for size, mine count, and possibly seed should all be ints, however, the decimal point input button isn't disabled, so inputs like 42.33 can be entered for the game height, for example.

No crashes observed, the game falls back to default values for the params.

Reproduction should be straightforward.

Android 12

App version
17.1.7S

**Comment by lucasnlm** [comment]
Thanks for reporting this bug!
It was fixed and should be available on the next update.
:)
