### ISSUE TITLE
A display problem

### ISSUE THREAD

**Issue by ChaserRuttan** [lucasnlm/antimine-android#420]
![IMG_20230406_135909.jpg](https://user-images.githubusercontent.com/67410761/230285092-bad77781-bbf7-4bef-89e3-acd6d6139447.jpg)

The display at the bottom of the screen has a frosted glass effect

**Comment by lucasnlm** [comment]
@ChaserRuttan do your phone have a visible navigation bar? Or do you use gestures?

This blur effect should be under the navigation bar.

**Comment by ChaserRuttan** [comment]
@lucasnlm My phone uses gestures and doesn't use the navigation bar
Like this ![Screenshot_20230408_180048.jpg](https://user-images.githubusercontent.com/67410761/230715483-d99be6de-6f54-45f8-920b-2edd28078093.jpg)

**Comment by lucasnlm** [comment]
I will remove this effect permanently. Since I don't have a trustful way to check if navigation bar is visible or not and I think this effect is not so good, I will remove it.

**Comment by ChaserRuttan** [comment]
> I will remove this effect permanently. Since I don't have a trustful way to check if navigation bar is visible or not and I think this effect is not so good, I will remove it.

Now many people use gestures to operate, this kind of blur effect is really not very good.Looking forward to the next update
