### ISSUE TITLE
instant crash

### ISSUE THREAD

**Issue by paulle** [lucasnlm/antimine-android#425]
**Describe the bug** starting the app causes instant crash

**To Reproduce**

**What control style do you use?**
You can check which control is selected on "Controls" screen.

**Expected behavior**

**Screenshots**

**Android Version:**12

**App Version** latest

**Comment by paulle** [comment]
Instant crash when starting the app.
Android 12. Xperia 5 Iii

**Comment by Quantenzitrone** [comment]
probably duplicate of #422

**Comment by paulle** [comment]
It seems so

Gesendet von Proton Mail für Mobilgeräte

-------- Original-Nachricht --------
Am 19. Apr. 2023, 19:19, schrieb Quantenzitrone :
