### ISSUE TITLE
instant crash 

### ISSUE THREAD

**Issue by vp800** [lucasnlm/antimine-android#426]
The app crashes immediately when opened.

Android 9 PKQ
Phone Redmi Note 8T

App Version:
version from f-droid 17.1.5, 17.1.7 F, 17.2.0 F
The previous version worked (17.0.0, 17.0.1)

**Comment by SuspectTyrannosaurus** [comment]
F-droid specific again, like #411 ?

**Comment by vp800** [comment]
Yes, only f-droid apps crash
But the app from [here](https://github.com/lucasnlm/antimine-android/releases/tag/17.1.7) works for me
