### ISSUE TITLE
Open/Flag button play sound effects even with sound effects off

### ISSUE THREAD

**Issue by supasonix-zuv** [lucasnlm/antimine-android#434]
**Describe the bug**
When tapping on the button to change between open & flag it plays a sound effect. I have sfx disabled in the settings menu.

**To Reproduce**
Switch from open to flag in a game

**What control style do you use?**
Use button to switch from flag to open

**Expected behavior**
No sfx play

**Screenshots**
![Screenshot_20230426-134352_Antimine_1cropped_1drawn](https://user-images.githubusercontent.com/71128937/234660302-48401458-ae65-462a-93ae-f4a888c075b5.png)

**Android Version:**
Lineage 19.1
**App Version**
17.2.2F

**Comment by lucasnlm** [comment]
Hi!
Thanks for your feedback.
It should be fixed in 17.2.3.

**Comment by supasonix-zuv** [comment]
Just updated and, yup it's gone. Thanks!
