### ISSUE TITLE
Bomb spawn in the corner

### ISSUE THREAD

**Issue by hiter67** [lucasnlm/antimine-android#443]
[Screenshot_20230507-163010_Anti-Mine.png](https://user-images.githubusercontent.com/47510277/236680518-098bbf5c-5b1b-449c-842a-2e0e9c88a941.png)

**Comment by Hiter67** [comment]
> Possibly you can figure out it was there by considering the 'mine counter' in the endgame. If there's only one remaining mine and only one square.

Yes, this is a variant of solving the puzzle, but the numbers do not really converge :(

**Comment by lucasnlm** [comment]
Since this behavior is hard to reproduce in the newest version (due to algorithm change), I will close this issue.
Thanks for reporting!
