### ISSUE TITLE
Missing statitics for master level.

### ISSUE THREAD

**Issue by talineo** [lucasnlm/antimine-android#451]
**Describe the bug**
In the statistics panel, I cannot see the panel for master level.

**To Reproduce**
Open the app, go to statistics panel, search for master level stats.

**Expected behavior**
In the statistics panel, I expect to see the panel for master level stats.

**Android Version:**
Android 12 on oneplus 7

**App Version**
f-droid version 17.2.3 F, in french.

**Comment by talineo** [comment]
from what I have seen, isMaster in app/src/main/java/dev/lucasnlm/antimine/stats/viewmodel/StatsViewModel.kt should be updated to test for 450 mines

**Comment by lucasnlm** [comment]
Hi! Thanks for report this bug.
I will fix it in the next version.
Probably available next week.
