### ISSUE TITLE
Colored numbers option

### ISSUE THREAD

**Issue by Dacid99** [lucasnlm/antimine-android#458]
Coloring the numbers in a characteristic color (eg 1 in blue, 2 in green, etc) would be helpful to quickly identify and distinguish them.
This could be a feature that can be toggled on or off in the options.
Thanks for your great work, i absolutely love the project and play every day (my girlfriend does too)!

**Comment by Samurai1201** [comment]
Thabks for the quick reply! Yes thats exactly what i mean

**Comment by lucasnlm** [comment]
No. There's no settings to do that.
Actually it used to be like this, but after the skins update I removed.
I will check how complex is to add the colors back. :+1:

**Comment by Samurai1201** [comment]
Nice thank you for your effort!

**Comment by Dacid99** [comment]
I just saw the latest version, thank you for bringing the colors back!
Im going to close this issue
