### ISSUE TITLE
Not possible to scroll

### ISSUE THREAD

**Issue by tasmo** [lucasnlm/antimine-android#461]
It used to be easy to scroll on big boards. It doesn't seem to be possible anymore.

I can easily zoom in and out but not go center the screen to any other position then the center of the board.

Does not work with any control setting.

Used to work with holding the finger on a tile and swipe.

Android Version: 13

Antimine Version: 17.4.0 F

**Comment by lucasnlm** [comment]
It's the same of #460. I hope to fix it soon.
