### ISSUE TITLE
App crashes when starting a Master or Legend game

### ISSUE THREAD

**Issue by jaschop-1k5o** [lucasnlm/antimine-android#468]
**Describe the bug**
App goes to loading screen for a split second, then closes.

**To Reproduce**
Select new game -> Master/Legend

**Android Version:**
13
**App Version**
17.5.1 F

**Comment by NeatNit** [comment]
Doesn't crash for me. What are your settings?

**Comment by jaschop-1k5o** [comment]
{
      "new_themes_icon_v2": false,
      "open_directly": true,
      "control_style": 2,
      "music": false,
      "show_windows": false,
      "progressive_value": 25,
      "show_tutorial_dialog": false,
      "long_press_timeout": 400,
      "show_continue": true,
      "simon_tatham": true,
      "use_help": false,
      "last_version": 1705011,
      "use_count": 48,
      "default_switch_button": 1,
      "should_show_tutorial_button": false,
      "current_tips": 100,
      "dim_numbers": false,
      "package": "dev.lucasnlm.antimine"
    }

**Comment by NeatNit** [comment]
Welp, now it crashes for me on Legend as well.

**Comment by lucasnlm** [comment]
Thanks for report!
This crash was fixed and It will be available in the next version.

**Comment by jaschop-1k5o** [comment]
Legend works great now on v17.5.10F
Many thanks!
