### ISSUE TITLE
Creating a custom game with very large size finishes game instantly

### ISSUE THREAD

**Issue by tetralovania** [lucasnlm/antimine-android#469]
**Describe the bug**
Creating a very large custom game, for example 10kx10k size with 100k bombs instantly finishes the game as if the player had won.

**To Reproduce**
Create a new game, select custom size, set width and height to 10k and bombs to 100k, then press anywhere on the field to start the game

**What control style do you use?**
(Irrelevant) Tap -> Flag, Double Tap -> Open

**Expected behavior**
Either create the gigantic game, or alternatively give an error and don't create the game.

**Android Version:**
13

**App Version**
17.5.0 F

**Comment by lucasnlm** [comment]
Hi!
Thanks for you message!
That is an expected behavior.
But I agree your you, it's looks like a bug.

I will add a visual feedback to it.

**Comment by lucasnlm** [comment]
<img src="https://github.com/lucasnlm/antimine-android/assets/1326126/e06f1fbf-d91b-498b-b7f6-d50f74974144" width="200px"/> <img src="https://github.com/lucasnlm/antimine-android/assets/1326126/13dd1ca4-aed4-4f1c-bd0e-69476ea31685" width="200px"/>

Added visual feedback. Now the user will know that values are crazy.
It will still allow create levels with high density, but at lease it has a warning now.
