### ISSUE TITLE
Going back freezes the game

### ISSUE THREAD

**Issue by Monniasza** [lucasnlm/antimine-android#479]
**Describe the bug**
When I go back from a game, the game hangs until task manager is open and then after going back into Antimine

**To Reproduce**
Press th in-game Back button

**What control style do you use?**
You can check which control is selected on "Controls" screen.

**Expected behavior**
I am immediately in the main menu

**Android Version:**
11 RKQ 201004.002

**App Version**
17.5.8 F

**Comment by lucasnlm** [comment]
@Monniasza Can you record a video with bug?
I can't reproduce it following the steps.

**Comment by Monniasza** [comment]
Start a game, finish it, and then press the left arrow on the screen

**Comment by lucasnlm** [comment]
@Monniasza Can you check if it happens on the latest version?

**Comment by Monniasza** [comment]
Thanks. It's now fixed
