### ISSUE TITLE
Accessing most pages (maybe menus) when loading one of some of the themes crashes the game

### ISSUE THREAD

**Issue by Scratchbin** [lucasnlm/antimine-android#481]
**Describe the bug**
When one of the certain themes are loaded, accessing any of most of the pages (seemingly menus excluding the main menu) of this game will lead into a crash; but **in this situation** neither creating nor accessing a game round will crash the game.

**To Reproduce**
Run the game. Enter the "Theme" page. Access one of the certain themes.

**What control style do you use?**
Hold to open; tap to place flag.

**Expected behavior**
No crashes were caused, pages run fine without problem.

**Screenshots**
-

**Android Version:**
Android 11 (MIUI 12.5.4.0, Mainland China)

**App Version**
17.5.8 F

**Comment by lucasnlm** [comment]
This issue was already fixed in the latest version (not published by F-droid yet).

**Comment by lucasnlm** [comment]
Can you check if it happens on the latest version? @Scratchbin

**Comment by Scratchbin** [comment]
Yes. The problem is solved.

**Comment by lucasnlm** [comment]
Thanks for confirming!
