### ISSUE TITLE
add possibility to replay a game

### ISSUE THREAD

**Issue by DJCrashdummy** [lucasnlm/antimine-android#74]
just a little idea which came in my mind while testing your nice app:

some people maybe like to replay the one particular game which blew up at the end, because of wrong guesses... or they liked the layout or whatever.

**Comment by lucasnlm** [comment]
Thanks for your feedback :)

There's a new feature on `7.0.0` version (not yet on Play Store) that allows to replay the previous 15 games. It's almost what you requested, but I think it should be nice to have "Replay" button on Game Over dialog.

The `Previous games` menu was added by #48.

**Comment by DJCrashdummy** [comment]
> Thanks for your feedback :)

thank **you** for making nice FOSS!

> There's a new feature on `7.0.0` version (not yet on Play Store) that allows to replay the previous 15 games.

interesting feature... but i hardly remember the last played one. :stuck_out_tongue_winking_eye: 
btw: no worries, i install my apps via f-droid. :wink: (no, they are also still at 6.3.2.)

> [...] it would be nice to have "Replay" button on Game Over dialog.

yes, that's what i thought about. sorry for not expressing it clearly.

**Comment by lucasnlm** [comment]
About F-Droid, it was added there this week. So I think `7.0.0` will be available soon.
And I really liked the idea of add a "Replay" button. I will probably add it. :smile:

**Comment by lucasnlm** [comment]
Replay feature will be added by #88.

**Comment by lucasnlm** [comment]
Completed. It will be available on `7.1.0`.

**Comment by DJCrashdummy** [comment]
is it on purpose that a first field is opened automatically after i taped on replay...? :confused:
