### ISSUE TITLE
Enable opening tiles by tapping numbers

### ISSUE THREAD

**Issue by Vas0sky** [lucasnlm/antimine-android#75]
In windows's minesweeper you can click with both left and right mouse buttons on a number tile and if it was surrounded by the same amount of mines its number was, it would openthe remaining surrounding tiles, whether the mines were correctly marked or not (in this case you would lose the game). There are other minesweeper clones that allow for this by simply tapping a number tile on android.

**Comment by lucasnlm** [comment]
Hi!
Thanks for your feedback!
Open tiles by tapping numbers is already possible on current implementation.
If you tap a number once it will highlight all its neighbors. If you long press a number it will open them.

**Comment by Vas0sky** [comment]
Oh I see, my bad I didn't try that. Well in this case maybe an option to use a single tap instead of a long press, that would make the game flow a bit better (afterall this is a game of finishing the table quick)

**Comment by lucasnlm** [comment]
I agree. Actually I need to add a "Controls" option before start the first game because some people don't link to use single click. I had some people requesting double click instead. So, I think the only solution for this issue is a "Control" option.

**Comment by Vas0sky** [comment]
Alright, I guess I can leave this issue open for now until a "Controls" panel is added, thank you very much.

**Comment by lucasnlm** [comment]
Hi! @Vas0sky 
Finnaly, the fast flag mode is available on `7.2.0`.
:smile:
