### ISSUE TITLE
Long-pressing a (>0) revealed tile ends the game

### ISSUE THREAD

**Issue by V3D3** [lucasnlm/antimine-android#96]
In all modes, when a tile has been revealed successfully:
- if tile indicates zero, long-tapping it (flagging it) does nothing
- (issue) if tile has a non-zero count on it, long-tapping it (flagging it) ends the game (all mines are blasted).

This is a bit problematic, since on a mobile screen you may misplace a flag (misplacing a flag should have no side effects, since placing it on a non-mine non-revealed tile does not end the game by the rules).

**Comment by lucasnlm** [comment]
I think that's actually a feature (it happens on Minesweeper from some newer Windows too). When you long press a numbered tile it open all its neighbors. If there is a mine in some of them it will be game over. If you flag the mine before long press the number it willl open all neighbors but won't open the flagged one.

This is a nice feature to help you open the field faster. But it still causes some trouble. I think I can add new verification to do not open all neighbors except if the number of flags is the same or bigger than the current long pressed tile. By doing this, it will be harder to miss click.

What do you think?

**Comment by V3D3** [comment]
I just tried it out, and it makes sense as a feature. I think I'll actually use it now 😅
A toggle for it would be wrong since it seems like a part of the game, so the extra rule is a great idea.

A prompt about it would be nice (or an introduction to the game where the controls are walked through)
